DECLARE
BEGIN
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE Queries';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE Advertisers';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE Keywords';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE Ads';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE !=-942 THEN
         RAISE;
      END IF;
END;
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE CACHE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE !=-942 THEN
      RAISE;
    END IF;
END;
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE TASK1';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE TASK2';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE TASK3';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE TASK4';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE TASK5';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE TASK6';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
BEGIN
EXECUTE IMMEDIATE 'DROP FUNCTION split';
EXCEPTION
  WHEN OTHERS THEN
     NULL;
END;
BEGIN
EXECUTE IMMEDIATE 'DROP FUNCTION getQuality';
EXCEPTION
  WHEN OTHERS THEN
    NULL;
END;
BEGIN
EXECUTE IMMEDIATE 'DROP TYPE VFLOAT';
EXCEPTION
  WHEN OTHERS THEN
    NULL;
END;
BEGIN
EXECUTE IMMEDIATE 'DROP TYPE VINFO';
EXCEPTION
  WHEN OTHERS THEN
    NULL;
END;
BEGIN
EXECUTE IMMEDIATE 'DROP TYPE INFO';
EXCEPTION
  WHEN OTHERS THEN
    NULL;
END;
BEGIN
EXECUTE IMMEDIATE 'DROP TYPE Tokens';
EXCEPTION
  WHEN OTHERS THEN
    NULL;
END;

EXECUTE IMMEDIATE 'CREATE TABLE Queries
(
qid	INTEGER,
query	VARCHAR(1000)
)';
EXECUTE IMMEDIATE 'CREATE TABLE Advertisers
(
advertiserId	INTEGER,
budget	FLOAT,
ctc	FLOAT
)';

EXECUTE IMMEDIATE 'CREATE TABLE Keywords
(
advertiserId	INTEGER,
keyword	VARCHAR(100),
bid	FLOAT
)';

EXECUTE IMMEDIATE'CREATE TABLE TASK1
(
qid	INTEGER,
rank	INTEGER,
advertiserId	INTEGER,
balance	FLOAT,
budget	FLOAT
)';

EXECUTE IMMEDIATE'CREATE TABLE TASK2
(
qid	INTEGER,
rank	INTEGER,
advertiserId	INTEGER,
balance	FLOAT,
budget	FLOAT
)';

EXECUTE IMMEDIATE'CREATE TABLE TASK3
(
qid	INTEGER,
rank	INTEGER,
advertiserId	INTEGER,
balance	FLOAT,
budget	FLOAT
)';

EXECUTE IMMEDIATE'CREATE TABLE TASK4
(
qid	INTEGER,
rank	INTEGER,
advertiserId	INTEGER,
balance	FLOAT,
budget	FLOAT
)';

EXECUTE IMMEDIATE'CREATE TABLE TASK5
(
qid	INTEGER,
rank	INTEGER,
advertiserId	INTEGER,
balance	FLOAT,
budget	FLOAT
)';

EXECUTE IMMEDIATE'CREATE TABLE TASK6
(
qid	INTEGER,
rank	INTEGER,
advertiserId	INTEGER,
balance	FLOAT,
budget	FLOAT
)';
END;
/
exit;
